- name: Pytest Coverage Action
  # You may pin to the exact commit or the version.
  # uses: twyle/oryks-code-coverage@ee94663168fe4fe1fce6cfe06b4ba05ffc755cf6
  uses: twyle/oryks-code-coverage@v0.17.1
  with:
    # The directory containing the source code.
    codedirectory: # optional, default is The project root i.e '.'
    # The directory containing the tests.
    testdirectory: # optional, default is tests\
    # The pycov configuration file
    pycovconfigfile: # optional, default is .coveragerc
    # The pytest configuration file.
    pytestconfigfile: # optional, default is setup.cfg
    # The GitHub Token.
    github_token: # optional, default is 
    # The Code Coverage token.
    oryks_token: # optional, default is 
